/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, Image, Pdf, Video } from "@boundaryml/baml"
import type * as types from "./types";
import type {
	Check,
	Checked,
	MediaType,
	MessageStatus,
	Resume,
	WhatsAppMessage,
	WhatsAppScreenshot,
} from "./types";

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
	value: T;
	state: "Pending" | "Incomplete" | "Complete";
}

export namespace partial_types {
	export interface Resume {
		name?: string | null;
		email?: string | null;
		experience: string[];
		skills: string[];
	}
	export interface WhatsAppMessage {
		date?: string | null;
		date_inferred?: boolean | null;
		time?: string | null;
		sender?: string | null;
		content?: string | null;
		media_type?: types.MediaType | null;
		media_description?: string | null;
		is_reply?: boolean | null;
		reply_preview?: string | null;
		is_forwarded?: boolean | null;
		is_edited?: boolean | null;
		message_status?: types.MessageStatus | null;
	}
	export interface WhatsAppScreenshot {
		chat_name?: string | null;
		chat_type?: string | null;
		messages: WhatsAppMessage[];
		visible_date_separators: string[];
		screenshot_context?: string | null;
		participant_count?: number | null;
	}
}
