/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum MediaType {
  Text = "Text",
  Image = "Image",
  Video = "Video",
  VoiceMessage = "VoiceMessage",
  Document = "Document",
  Sticker = "Sticker",
  Gif = "Gif",
  Contact = "Contact",
  Location = "Location",
  LinkPreview = "LinkPreview",
  Deleted = "Deleted",
  Poll = "Poll",
}

export enum MessageStatus {
  Sent = "Sent",
  Delivered = "Delivered",
  Read = "Read",
  Pending = "Pending",
  Unknown = "Unknown",
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface WhatsAppMessage {
  date: string
  date_inferred: boolean
  time: string
  sender: string
  content: string
  media_type: MediaType
  media_description?: string | null
  is_reply: boolean
  reply_preview?: string | null
  is_forwarded: boolean
  is_edited: boolean
  message_status?: MessageStatus | null
  
}

export interface WhatsAppScreenshot {
  chat_name: string
  chat_type: string
  messages: WhatsAppMessage[]
  visible_date_separators: string[]
  screenshot_context?: string | null
  participant_count?: number | null
  
}
